language: ruby
rvm:
  - "1.8.7"
  - "1.9.3"
  - "2.0.0"
  - "2.1.2"
  - "2.2.0"
gemfile:
  - gemfiles/Gemfile.3.2
  - gemfiles/Gemfile.4.0
  - gemfiles/Gemfile.4.1
  - gemfiles/Gemfile.4.2.1
  - gemfiles/Gemfile.4.2.1.pg
  - gemfiles/Gemfile.4.2.1.mysql2
before_script:
  - psql -c 'create database active_type_test;' -U postgres
  - mysql -e 'create database IF NOT EXISTS active_type_test;'
script: bundle exec rspec spec
notifications:
  email:
    - fail@makandra.de
branches:
  only:
    - master
matrix:
  exclude:
    - rvm: "1.8.7"
      gemfile: gemfiles/Gemfile.4.0
    - rvm: "1.8.7"
      gemfile: gemfiles/Gemfile.4.1
    - rvm: "1.8.7"
      gemfile: gemfiles/Gemfile.4.2.1
    - rvm: "1.8.7"
      gemfile: gemfiles/Gemfile.4.2.1.pg
    - rvm: "1.9.3"
      gemfile: gemfiles/Gemfile.4.2.1.pg
    - rvm: "2.0.0"
      gemfile: gemfiles/Gemfile.4.2.1.pg

    - rvm: "2.1.2"
      gemfile: gemfiles/Gemfile.3.2
    - rvm: "2.1.2"
      gemfile: gemfiles/Gemfile.4.0

    - rvm: "2.2.0"
      gemfile: gemfiles/Gemfile.3.2
    - rvm: "2.2.0"
      gemfile: gemfiles/Gemfile.4.0
